# (c) Copyright 2023 Hewlett Packard Enterprise Development LP

name: Helm Process

on:
  workflow_call:
    inputs:
      helm_package:
        type: string
        description: Helm package to upload to s3
        required: true
      version:
        type: string
        description: version tags for helm charts
        required: true

jobs:
  push-helm-chart:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Helm build
      shell: bash
      run: |
        helm package ${{ inputs.helm_package }} \
          --version ${{ inputs.version }} \
          --app-version ${{ inputs.version }} \
