# Copyright 2023 Hewlett Packard Enterprise Development LP
name: tag_manage
on:
  workflow_call:
    outputs:
      computed_tag:
         description: "The computed tag output string"
         value: ${{ jobs.tag-manage.outputs.tag_version }}

jobs:
  tag-manage:
    name: Generate Tag output
    runs-on: ubuntu-latest
 
   
    outputs:
      tag_version_dev: ${{ steps.dev.outputs.GIT_TAG }}
      tag_version_prod: ${{ steps.prod.outputs.GIT_TAG }}

    steps:
  
      - id: dev
        if: github.ref != 'refs/heads/main'
        run: |
          tag-manage create --min 0.1.1 --push -vv
          GIT_TAG=$(tag-manage describe --default 0.0.0)
          echo "GIT_TAG=v${GIT_TAG}" >> GIT_OUTPUT

      - id: prod
        if: github.ref == 'refs/heads/main'
        run: |
          tag-manage create --min 0.1.1 --push -vv
          GIT_TAG=$(tag-manage describe --default 0.0.0)
          echo "GIT_TAG=v${GIT_TAG}" >> GIT_OUTPUT
